import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from '@/contexts/auth-context'
import { WorkspaceProvider } from '@/contexts/workspace-context'
import { Sidebar } from '@/components/sidebar'
import { TaskPanel } from '@/components/task-panel'
import { GlobalLoader } from '@/components/global-loader'
import { TimerProvider } from '@/contexts/timer-context'
import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from "@vercel/speed-insights/next"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <WorkspaceProvider>
            <TimerProvider>
              <SpeedInsights />
              <Analytics />
              <GlobalLoader>
                <div className="flex h-screen bg-white">
                  <Sidebar />
                  <main className="flex-1 p-6">
                    {children}
                  </main>
                  <TaskPanel />
                </div>
              </GlobalLoader>
            </TimerProvider>
          </WorkspaceProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
