import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from '@/contexts/auth-context'
import { WorkspaceProvider } from '@/contexts/workspace-context'
import { Sidebar } from '@/components/sidebar'
import { TaskPanel } from '@/components/task-panel'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <WorkspaceProvider>
          <div className="flex h-screen bg-white">
              <Sidebar />
              <main className="flex-1 p-6">
                {children}
              </main>
              <TaskPanel />
            </div>
          </WorkspaceProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
